# Generated by Django 4.0 on 2021-12-24 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Amount should not be less than zero!')]),
        ),
    ]
