# Generated by Django 4.0 on 2022-01-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgettracker', '0002_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='acc1', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
